spring:
  batch:
    job:
      enabled: true
      name: demographicPlaceJob
  jpa:
    database: postgresql
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: @MASTER_DB_URL@
    username: @MASTER_DB_USERNAME@
    password: @MASTER_DB_PASSWORD@

logging:
  level:
    root: DEBUG
  slack:
    webhook-uri: @SLACK_WEBHOOK_URI@

decorator:
  datasource:
    p6spy:
      enable-logging: true

server:
  port: @PLACE_REGION_BATCH_PORT@

