import AuthContext from '@/context/AuthContext';
import type { Metadata } from 'next';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
import localFont from 'next/font/local';
import MSWComponent from './_components/MSWComponent';
import Header from './_components/header/Header';

const Jalnan = localFont({
  src: '../../public/fonts/Jalnan2TTF.ttf',
  display: 'swap',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className="max-w-[430px] mx-auto">
        <MSWComponent />
        <AuthContext>
          <Header />
          {children}
        </AuthContext>
      </body>
    </html>
  );
}
