spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  jpa:
    database: postgresql
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true
  datasource:
    master:
      hikari:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:5432/yigil-db
        #        jdbc-url: jdbc:postgresql://database-1.c90gu44yybro.ap-northeast-2.rds.amazonaws.com:5432/yigildb
        read-only: false
        username: postgres
        #        password: 12345678
        password: 1234
    slave:
      hikari:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:5433/yigil-db
        #        jdbc-url: jdbc:postgresql://database-1- read.c90gu44yybro.ap-northeast-2.rds.amazonaws.com:5432/yigildb
        read-only: true
        username: postgres
        #        password: 12345678
        password: 1234
  data:
    redis:
      host: localhost
      port: 6379
  jackson:
    property-naming-strategy: SNAKE_CASE

cloud:
  aws:
    s3:
    #      bucket: yigilbucket
    bucket: cdn.yigil.co.kr
    credentials:
      access-key: AKIA57RFG4SU5VO6U3PQ
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

server:
  servlet:
    session:
      cookie:
        http-only: true
        secure: false

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

logging:
  level:
    root: DEBUG
#  slack:
#    webhook-uri: https://hooks.slack.com/services/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

decorator:
  datasource:
    p6spy:
      enable-logging: true