spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  jpa:
    database: postgresql
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true
  datasource:
    master:
      hikari:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://database-1.c90gu44yybro.ap-northeast-2.rds.amazonaws.com:5432/yigildev
        read-only: false
        username: postgres
        password: 12345678
    slave:
      hikari:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://database-1- read.c90gu44yybro.ap-northeast-2.rds.amazonaws.com:5432/yigildev
        read-only: true
        username: postgres
        password: 12345678
  data:
    redis:
      host: localhost
      port: 6379

  jackson:
    property-naming-strategy: SNAKE_CASE

  mail:
    host: smtp.gmail.com
    port: 587
    username: kiit0901
    password: irbjczbuoksnjjad

    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

cloud:
  aws:
    s3:
    bucket: cdn.yigil.co.kr
    credentials:
      access-key: AKIA57RFG4SU5VO6U3PQ
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

server:
  port: 8081
  servlet:
    session:
      cookie:
        http-only: true
        secure: false

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

logging:
  level:
    root: DEBUG
  slack:
    webhook-uri: https://hooks.slack.com/services/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

jwt:
  secret: 64461f01e1af406da538b9c48d801ce59142452199ff112fb5404c8e7e98e3ff

decorator:
  datasource:
    p6spy:
      enable-logging: true