spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  jpa:
    database: postgresql
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
    show-sql: true
    properties:
      format_sql : true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  datasource:
    url: ENC(CLE/4mw1dFeX8rNwrN+66qUIBbo2dwOSQC5aKoEp3DJna2viB0VAtbugdRFL91XxSaYLpo9YlsQ=)
    username: ENC(7X2Dna+5eL+qNm2Yb6N3GO090wNqjMNA)
    password: ENC(7H6b3HZsLx/eRe4Ko7IlaA==)
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ENC(UgD5UNWpvBb7t/dN8aCRdGSI+zTQ/qMv)
      port: 6379

cloud:
  aws:
    s3:
      bucket: yigilbucket
    credentials:
      access-key: AKIA57RFG4SU5VO6U3PQ
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

server:
  servlet:
    session:
      cookie:
        http-only: true
        secure: false

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

logging:
  level:
    root: INFO
  slack:
    webhook-uri: https://hooks.slack.com/services/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

